# Generated by Django 5.0.7 on 2024-12-28 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='created_at',
            new_name='submitted_at',
        ),
    ]
