# Generated by Django 5.0.7 on 2024-12-07 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_contactmessage_delete_enquiry_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
    ]
