# Generated by Django 5.0.7 on 2024-12-28 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUs',
        ),
    ]
