# Generated by Django 5.0.7 on 2024-12-28 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '0005_delete_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='enquiry_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=10)),
                ('message', models.TimeField()),
            ],
        ),
    ]
