# Generated by Django 5.0.7 on 2024-12-29 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_rename_created_at_registration_submitted_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
