# Generated by Django 5.0.7 on 2025-01-23 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
