# Generated by Django 5.0.7 on 2025-01-28 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
