# Generated by Django 5.0.7 on 2025-01-29 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0016_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
