# Generated by Django 5.0.7 on 2025-03-23 13:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0017_delete_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry_table',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
