# Generated by Django 5.0.7 on 2025-03-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0018_enquiry_table_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('service_type', models.CharField(choices=[('ppf', 'Paint Protection Film'), ('wrap', 'Car Wrapping'), ('detail', 'Car Detailing'), ('mod', 'Car Modification'), ('repair', 'Accidental Repair')], max_length=20)),
                ('appointment_date', models.DateField()),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
