# Generated by Django 5.0.7 on 2025-03-23 13:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0019_servicebooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebooking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
