# Generated by Django 5.2 on 2025-09-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0020_servicebooking_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry_table',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
