# Generated by Django 5.2 on 2025-09-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0021_enquiry_table_is_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebooking',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
